### ISSUE TITLE
Randomly learned abilities only for singular jobs

### ISSUE THREAD

**Issue by randoomdude** [TojiKitten/FFTA-randomizer#74]
I don't think there's any option to have a character start as a job with only 3-4 random abilities instead of a mastered for all of them, or having something like Blue Mage but instead of every single one mastered just a couple so it's balanced a little, maybe a check box next to number of abilities that says "only for this job

Also maybe the ability to only randomize certain jobs... sorry just thinking up additions as I write this out, you know just if you want to add it

**Comment by randoomdude** [comment]
Been playing the randomizer all day and having a blast, do you know if it's possible to change our Marche/Montblanc in party randomizer and maybe also put in bonus characters like Ritz/Babus?

**Comment by fgkeiji** [comment]
@randoomdude, you're correct that there's nothing in the current version to specifically target a random number of abilities for specific jobs. The options are a number of random abilities across all jobs or mastering a random number of jobs. The first option sounds closer to what you're looking for, but not exact.

Marche and Monty must be in the party, but you can roll them as any race instead of being locked to human and moogle, respectively. I received another request to allow guest characters, so that is one we've heard people would like.

**Comment by fgkeiji** [comment]
This has been added to version 3.2.3
